version: "3.8"

services:
  postgres:
    image: postgres:16.2-alpine
    container_name: db_online_store
    restart: always
    environment:
      POSTGRES_DB: online-store
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d online-store"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - netgo

  redis:
    image: redis
    container_name: redis_online_store
    restart: always
    ports:
      - 6377:6379
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  # jika ingin membuka mongo express : localhost:8081,
  # jika dimintai pw. user:admin pw, pass
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  backend:
    container_name: gostore
    image: zikrigusli/onlinestore:4
    ports:
      - "8083:8082" # Sesuai dengan port di Dockerfile
    environment:
      DB_HOST: db_online_store
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - netgo

networks:
  netgo:
    name: "netstore"
    external: false
