app:
  name: synapsis-online-store
  port: ":8081"
  encryption:
    salt: 10
    jwt_secret: adfhkjdhjadh

db:
  # untuk variable ini diganti menggunakan .env file untuk kemudahan build docker
  # start env file
  host: localhost
  port: 5432
  user: admin
  password: admin
  name: online-store
  #  end env file
  connection_pool:
    max_idle_connection: 10
    max_open_connection: 30
    max_lifetime_connection: 60 #second
    max_idletime_connection: 60
