app:
  name: nbid-online-shop
  port: ":8081"
  encryption:
    salt: 10
    jwt_secret: adfhkjdhjadh

db:
  host: localhost
  port: 5432
  user: admin
  password: admin
  name: ticket
  connection_pool:
    max_idle_connection: 10
    max_open_connection: 30
    max_lifetime_connection: 60 #second
    max_idletime_connection: 60
